version: 2.1
orbs:
  go: circleci/go@1.5.0

jobs:
  # This job builds the hive executable and stores it in the workspace.
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      # Build it.
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: {command: "go build ."}
      # Store the executable.
      - persist_to_workspace:
          root: .
          paths: ["hive"]

  # This job runs the go unit tests.
  go-test:
    docker:
      - image: cimg/go:1.17
    steps:
      # Get the source.
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      # Run the tests.
      - run:
          name: "hive module tests"
          command: "go test -cover ./..."
      - run:
          name: "hiveproxy module tests"
          command: "go test -cover ./..."
          working_directory: "./hiveproxy"
      - run:
          name: "Compile Go simulators"
          command: ".circleci/compile-simulators.sh"
  rust-simulators:
      docker:
        - image: cimg/rust:1.75.0
      steps:
        - checkout
        - run:
            name: Install rustfmt
            command: rustup component add rustfmt
        - run:
            name: Install Clippy
            command: rustup component add clippy
        - run:
            name: Install Clang
            command: sudo apt update && sudo apt-get install clang -y
        - run:
            name: "Lint, build, test Rust simulators"
            command: ".circleci/rust-simulators.sh"
  build-simulator-dockerfile:
    docker:
      - image: cimg/base:2022.06
    # parallelism level should be set to the amount of simulators we have or greater
    # The reason for this is the CI code currently only supports 1 input at a time
    # if we have a parallelism level of 5 and 6 sims one test runner will get 2 test sims and fail
    parallelism: 7
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          name: "Build dockerfile for simulator"
          command: |
            SimDockerfile=$(circleci tests glob "simulators/**/Dockerfile" | circleci tests split --split-by=timings)
            echo "Building Docker file: $SimDockerfile"
            docker build -f $SimDockerfile .
workflows:
  main:
    jobs:
      - go-test
      - build
      - rust-simulators
      - build-simulator-dockerfile
